# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Jaén 2018"
email: "gdgjaen@gmail.com"
description: "GDG DevFest Jaén 2018. El punto de encuentro con tu comunidad local"
baseurl: ""
url: "https://devfest.gdgjaen.me"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "GDG Jaén"
organizerAlternateName: "GDG Jaén"
organizerDescription: "GDG Jaén es una entidad sin ánimo de lucro creada con el objetivo de mejorar la comunidad de entusiastas tecnológicos y aumentar el conocimiento y las relaciones entre las personas que se dedican a esta área."
organizerEmail: "gdgjaen@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgjaen.me"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, jaen"
twitterAccount: "@GDGJaen"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://t.co/2fSHWKyjkn"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Organizadores"}
rightNavigationButtons:
 - {link: "https://www.meetup.com/es/GDG-Jaen/events/253163269/", text: "Compra tu entrada"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest Jaén"
eventDate: "17 de noviembre"
typeoutTextValues: '"", " 2018", " Season", " Jaen"'
typeoutFallback: " Season"
heroButtons:
 - {link: "https://www.meetup.com/es/GDG-Jaen/events/253163269/", text: "Compra tu entrada"}

# About Block
aboutTitle: "Sobre GDG DevFest Jaén"
aboutBlock:
 - {title: "Ponentes", image: "conference.jpg", text: "Ponentes de primer nivel venidos desde toda España" }
 - {title: "Comunidad", image: "workshop.jpg", text: "Reúnete con la mayor comunidad de tecnólogos entusiastas de la provincia" }
 - {title: "Tecnología", image: "hackathon.jpg", text: "Ven y aprende con nosotros sobre las tecnologías más novedosas" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "450", specialCharacter: "+", info: "asistentes", detail: "y tú tienes que ser uno de ellos"}
 - {count: "10", specialCharacter: "+", info: "hours", detail: "horas de tecnología"}
 - {count: "15", specialCharacter: "+", info: "ponentes", detail: "de primer nivel"}
 - {count: "3", specialCharacter: "", info: "tracks paralelos", detail: "para que tengas dónde elegir"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 15
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Saber más"

# Location Block
locationBlockTitle: "Localización"
eventLocationName: "Edificio B4 Universidad de Jaén"
eventLocationLink: "https://uja.es"
eventStreetAddress: "Campus Las Lagunillas, s/n"
eventAddressLocality: "Jaén"
eventAddressLocalityRegion: "Jaén"
eventPostalCode: "23071"
eventAddressCountry: "España"
eventStartTime: "2018-11-16T09:30"
eventDoorTime: "09:15"
eventEndTime: "2018-11-16T20:00"
eventPlaceCoordinates: "37.788385, -3.777133"
mapCenterCoordinates: "37.788385, -3.777133"
mapMobileCenterCoordinates: "37.788385, -3.777133"

# Venue Block
venueBlockTitle: "¿Dónde vamos a celebrar el evento?"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Edificio B4, Universidad de Jaén"
venueFeatures: ["Campus Las Lagunillas, s/n, 23071 Jaen", "http://ujaen.es/"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Quieres seguir el evento por redes sociales?"
twitterHashTag: "devfestjaen"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "El registro es obligatorio si quieres participar en todas nuestras actividades, tener posibilidad de participar en los concursos realizados durante el evento y... ¡mucho más!"
ticketsOffers:
 -
  name: "Early Bird"
  price: "3.5"
  priceCurrency: "EUROS"
  ticketsNumber: "450"
  ribbon: "-30%"
  featured: true
  buyButtonLink: "https://www.meetup.com/es/GDG-Jaen/events/253163269/"
  buyButtonText: "Compra"
  ticketContentList: ["Entrada a charlas y talleres", "Almuerzo y Coffee Break", "Cositas intersantes"]
  validFrom: "2018-08-25T10:00"
  validThrough: "2018-11-1T00:00"
 -
  name: "Normal"
  price: "5"
  priceCurrency: "EUROS"
  ticketsNumber: "450"
  ribbon: ""
  buyButtonLink: "https://www.meetup.com/es/GDG-Jaen/events/253163269/"
  buyButtonText: "Compra"
  ticketContentList: ["Entrada a charlas y talleres", "Almuerzo y Coffee Break", "Cositas intersantes"]
  soldOut: true
  soldOutText: "Empezando el 20 de Octubre"

# Footer
socialLinks:
 - {link: "https://twitter.com/GDGJaen", icon: "twitter"}
 - {link: "https://facebook.com/GDGJaen", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgjaen.me", text: "GDG Jaén"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:gdgjaen@gmail.com", text: "gdgjaen@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conducta"}

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nosotros"
aboutUs: "Los Google Developer Groups (GDGs) son entidades sin ánimo de lucro creadas con el objetivo de mejorar la comunidad de entusiastas tecnológicos y aumentar el conocimiento y las relaciones entre las personas que se dedican a esta área. GDG Jaén es la rama local de esta comunidad."